### ISSUE TITLE
The underline control is broken when creating homework

### ISSUE THREAD

**Issue by ivanhrabcak** [7274-dev/AdventnaVyzva-React#12]
It underlines the whole line, not just selected text, if you click it multiple times it just adds more underlines.

**Comment by Streamer272** [comment]
Well, it is browser executed, so make sure you are running latest version of chrome because we can't do shit about this. This is the code for it
document.exec("underline")

**Comment by Streamer272** [comment]
*document.execCommand("underline")

**Comment by ivanhrabcak** [comment]
> Well, it is browser executed, so make sure you are running latest version of chrome because we can't do shit about this. This is the code for it
document.execCommand("underline")


I will try to find a better way to do this.

**Comment by ivanhrabcak** [comment]
This issue to my knowlege hasn't been fixed yet, reopening.
