### ISSUE TITLE
Showing students something else than image doesn't work

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-React#14]
When teacher has attached something else than a image, this doesnt get displayed, since we dont take it into account
![image](https://user-images.githubusercontent.com/49731971/142479301-e06d9b30-63f0-4cc2-ab47-962af39347b7.png)

**Comment by Streamer272** [comment]
Make mapping on backend for getting file type

**Comment by Streamer272** [comment]
Not done yet, render error occurs for some reason

**Comment by Streamer272** [comment]
Resolved in commit 9f0eb0f73e9378d33dc36af700614130e17224d7
Backend was the issue, fixed in commit 02f58c6079bfaf866463e41a6dba06d2b16d947c
