### ISSUE TITLE
Image scale is preserved on student page and it can mess things up

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-React#6]
![image](https://user-images.githubusercontent.com/49731971/141145513-7c6f0e14-ce44-487c-b8ca-04446d99eb24.png)
When a large image is uploaded it's scale is preserved, which means that it is too large to show

**Comment by Streamer272** [comment]
Fixed in 772553e7971bce594123fa6b22a1be739d874ea0
All images and videos now have
`max-width: 100%;`
