### ISSUE TITLE
Change snowflake count toast should wait for user to stop typing

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-React#7]

**Comment by Streamer272** [comment]
Fixed in commit 446e127305431bdfe64a64db95d64f47844545de
Snowflake toast now only shows after settings close

**Comment by MagSG-7274** [comment]
Also when you select too high a number, it still spams

**Comment by Streamer272** [comment]
Create another issue for that

**Comment by Streamer272** [comment]
Fixed in commit 6f09fc375f0539d308c1d7266ac1b7d573162778
Solution:
    can only send error message every 5000ms milliseconds (time it takes toast (info) to delete itself automatically)
    messages don't stack up to each other (if you edit snowflakes count while toast is online it will not send another error, for that to happen you have to edit AFTER the previous toast error timer runs out)
